TIMEOUT 30
DEFAULT p450-sdmmc3-uartb460800-nokmem

MENU TITLE L4T boot options

LABEL p450-sdmmc3-uartb460800-nokmem
      MENU LABEL P450 SDMMC3 + Wi-Fi + UARTB 460800 + memcg kmem off
      LINUX /boot/Image
      FDT /boot/dtb/p450-p3668-0001-p3509-0000-sdmmc3-wifi-uartb460800.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb cgroup.memory=nokmem

LABEL p450-sdmmc3-uartb460800
      MENU LABEL P450 SDMMC3 + Wi-Fi + UARTB 460800 baud fix
      LINUX /boot/Image
      FDT /boot/dtb/p450-p3668-0001-p3509-0000-sdmmc3-wifi-uartb460800.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb

LABEL p450-sdmmc3
      MENU LABEL P450 SDMMC3 + Intel Wi-Fi GPIO fix
      LINUX /boot/Image
      FDT /boot/dtb/p450-p3668-0001-p3509-0000-sdmmc3-wifi.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb

LABEL sd-force
      MENU LABEL previous SDMMC1 force-probe DTB
      LINUX /boot/Image
      FDT /boot/dtb/kernel_tegra194-p3668-0001-p3509-0000-force-sd.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb

LABEL sd-enabled
      MENU LABEL previous SDMMC1 card-detect DTB
      LINUX /boot/Image
      FDT /boot/tegra194-p3668-all-p3509-0000.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb

LABEL original
      MENU LABEL original eMMC-only kernel/device tree (fallback)
      LINUX /boot/Image
      FDT /boot/dtb/kernel_tegra194-p3668-0001-p3509-0000.dtb
      INITRD /boot/initrd
      APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyTCU0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 video=efifb:off nospectre_bhb
